using Xunit;

namespace AbpIoTemplateProject.EntityFrameworkCore;

[CollectionDefinition(AbpIoTemplateProjectTestConsts.CollectionDefinitionName)]
public class AbpIoTemplateProjectEntityFrameworkCoreCollection : ICollectionFixture<AbpIoTemplateProjectEntityFrameworkCoreFixture>
{

}
