using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Services;

namespace AbpIoTemplateProject.Education;

public interface IAdminEducationAppService : IApplicationService
{
    Task<EducationDashboardDto> GetDashboardAsync();
    Task<List<AdminCourseDto>> GetCoursesAsync();
    Task<UpsertCourseDto> GetCourseForEditAsync(Guid id);
    Task<Guid> CreateCourseAsync(UpsertCourseDto input);
    Task UpdateCourseAsync(Guid id, UpsertCourseDto input);
    Task DeleteCourseAsync(Guid id);
    Task<List<AdminTeacherDto>> GetTeachersAsync();
    Task<UpsertTeacherDto> GetTeacherForEditAsync(Guid id);
    Task<Guid> CreateTeacherAsync(UpsertTeacherDto input);
    Task UpdateTeacherAsync(Guid id, UpsertTeacherDto input);
    Task DeleteTeacherAsync(Guid id);
    Task<List<AdminCourseClassDto>> GetClassesAsync();
    Task<UpsertCourseClassDto> GetClassForEditAsync(Guid id);
    Task<Guid> CreateClassAsync(UpsertCourseClassDto input);
    Task UpdateClassAsync(Guid id, UpsertCourseClassDto input);
    Task DeleteClassAsync(Guid id);
    Task<List<SelectOptionDto>> GetCourseOptionsAsync();
    Task<List<SelectOptionDto>> GetTeacherOptionsAsync();
    Task<List<SelectOptionDto>> GetCampusOptionsAsync();
    Task<List<AdminStudentDto>> GetStudentsAsync();
    Task<UpsertStudentDto> GetStudentForEditAsync(Guid id);
    Task<Guid> CreateStudentAsync(UpsertStudentDto input);
    Task UpdateStudentAsync(Guid id, UpsertStudentDto input);
    Task DeleteStudentAsync(Guid id);
    Task<List<AdminEnrollmentDto>> GetEnrollmentsAsync();
    Task<Guid> CreateEnrollmentAsync(UpsertEnrollmentDto input);
    Task DeleteEnrollmentAsync(Guid id);
    Task<List<AdminArticleDto>> GetArticlesAsync();
    Task<UpsertArticleDto> GetArticleForEditAsync(Guid id);
    Task<Guid> CreateArticleAsync(UpsertArticleDto input);
    Task UpdateArticleAsync(Guid id, UpsertArticleDto input);
    Task DeleteArticleAsync(Guid id);
    Task<List<SelectOptionDto>> GetArticleCategoryOptionsAsync();
    Task<List<AdminDocumentDto>> GetDocumentsAsync();
    Task<UpsertDocumentDto> GetDocumentForEditAsync(Guid id);
    Task<Guid> CreateDocumentAsync(UpsertDocumentDto input);
    Task UpdateDocumentAsync(Guid id, UpsertDocumentDto input);
    Task DeleteDocumentAsync(Guid id);
    Task<List<AdminPlacementTestDto>> GetPlacementTestsAsync();
    Task<UpsertPlacementTestDto> GetPlacementTestForEditAsync(Guid id);
    Task<Guid> CreatePlacementTestAsync(UpsertPlacementTestDto input);
    Task UpdatePlacementTestAsync(Guid id, UpsertPlacementTestDto input);
    Task DeletePlacementTestAsync(Guid id);
    Task<List<AdminPlacementQuestionDto>> GetPlacementQuestionsAsync(Guid testId);
    Task<UpsertPlacementQuestionDto> GetPlacementQuestionForEditAsync(Guid id);
    Task<Guid> CreatePlacementQuestionAsync(Guid testId, UpsertPlacementQuestionDto input);
    Task UpdatePlacementQuestionAsync(Guid id, UpsertPlacementQuestionDto input);
    Task DeletePlacementQuestionAsync(Guid id);
    Task<List<AdminLeadDto>> GetLeadsAsync();
    Task UpdateLeadStatusAsync(Guid id, UpdateLeadStatusDto input);
}
