$ErrorActionPreference = 'Stop'
$toolRoot = Split-Path $PSScriptRoot -Parent
$repoRoot = Split-Path (Split-Path $toolRoot -Parent) -Parent
$destination = Join-Path $repoRoot 'src/WebHoanTien.Web/wwwroot/tools/shopee-settlements'
$background = Get-Content -LiteralPath (Join-Path $toolRoot 'extension/background.js') -Raw
$start = $background.IndexOf('async function collectShopeeSettlementRowsInPage(')
$end = $background.IndexOf('class UserFacingError', $start)
if ($start -lt 0 -or $end -le $start) { throw 'Không tìm thấy collector trong background.js.' }
$collector = $background.Substring($start, $end - $start)
$interceptor = Get-Content -LiteralPath (Join-Path $toolRoot 'extension/billing-network-interceptor.js') -Raw
$mobile = Get-Content -LiteralPath (Join-Path $PSScriptRoot 'runner.js') -Raw
$bundle = @"
// Generated by Tool/catsback-shopee-sync/mobile/build.ps1. Do not edit.
(() => {
if (location.origin !== 'https://affiliate.shopee.vn') {
  alert('Hãy mở và đăng nhập https://affiliate.shopee.vn/payment/billing trước khi chạy CatsBack.');
  return;
}
if (document.getElementById('catsback-mobile-settlements')) return;
$interceptor
$collector
$mobile
})();
"@
[System.IO.Directory]::CreateDirectory($destination) | Out-Null
[System.IO.File]::WriteAllText((Join-Path $destination 'bookmarklet.js'), $bundle, [System.Text.UTF8Encoding]::new($false))
Write-Output 'Đã tạo bookmarklet.js từ collector dùng chung với extension.'
