$ErrorActionPreference = 'Stop'
$toolRoot = Split-Path $PSScriptRoot -Parent
$repoRoot = Split-Path (Split-Path $toolRoot -Parent) -Parent
$destination = Join-Path $repoRoot 'src/WebHoanTien.Web/wwwroot/tools/shopee-settlements'
$background = Get-Content -LiteralPath (Join-Path $toolRoot 'extension/background.js') -Raw -Encoding UTF8
$start = $background.IndexOf('async function collectShopeeSettlementRowsInPage(')
if ($start -lt 0) { throw 'Không tìm thấy collector trong background.js.' }
$end = $background.IndexOf('class UserFacingError', $start)
if ($end -le $start) { throw 'Không tìm thấy phần kết thúc collector trong background.js.' }
$collector = $background.Substring($start, $end - $start)
$interceptor = Get-Content -LiteralPath (Join-Path $toolRoot 'extension/billing-network-interceptor.js') -Raw -Encoding UTF8
$mobile = Get-Content -LiteralPath (Join-Path $PSScriptRoot 'runner.js') -Raw -Encoding UTF8
$bundle = @"
// Generated by Tool/catsback-shopee-sync/mobile/build.ps1. Do not edit.
(() => {
try {
if (location.origin !== 'https://affiliate.shopee.vn') {
  alert('Hãy mở và đăng nhập https://affiliate.shopee.vn/payment/billing trước khi chạy CatsBack.');
  return;
}
const existingPanel = document.getElementById('catsback-mobile-settlements');
if (existingPanel) {
  existingPanel.dispatchEvent(new Event('catsback:show'));
  return;
}
$interceptor
$collector
$mobile
} catch (error) {
  document.getElementById('catsback-mobile-settlements')?.remove();
  alert('CatsBack không mở được bảng điều khiển: ' + (error?.message || String(error)) + '\nHãy gửi lại nguyên thông báo này để kiểm tra.');
}
})();
"@
[System.IO.Directory]::CreateDirectory($destination) | Out-Null
[System.IO.File]::WriteAllText((Join-Path $destination 'bookmarklet.js'), $bundle, [System.Text.UTF8Encoding]::new($false))
& node (Join-Path $PSScriptRoot 'minify.mjs')
if ($LASTEXITCODE -ne 0) { throw 'Không tạo được mã dấu trang rút gọn. Cài dependencies trong src/WebHoanTien.Web bằng npm ci rồi chạy lại.' }
Write-Output 'Đã tạo bookmarklet.js và catsback-json-bookmarklet.txt từ collector dùng chung với extension.'
