<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>WebHoanTien</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\WebHoanTien.EntityFrameworkCore\WebHoanTien.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\WebHoanTien.Application.Tests\WebHoanTien.Application.Tests.csproj" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.14.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
  </ItemGroup>

</Project>
